<?php
// module/Album/view/album/album/edit.phtml:
 
$title = 'Article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo "</br>";
echo $this->formRow($form->get('category'));
echo "</br>";
echo $this->formRow($form->get('title'));
echo "</br>";
echo $this->formRow($form->get('content'));
echo "</br>";
echo $this->formRow($form->get('time_created'));
echo "</br>";
echo $this->formRow($form->get('author'));
echo "</br>";
echo $this->formRow($form->get('status'));
echo "</br>";
echo $this->formRow($form->get('img'));
echo "</br>";


// echo $this->formCollection($form);

echo $this->form()->closeTag();
