<?php
// module/Album/view/album/album/index.phtml:

$title = 'Olivet University';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add News</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Category</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td> <a href="<?php echo $this->url('album',
            array('action'=>'article', 'id' => $album->id));?>"><?php echo $this->escapeHtml($album->title);?></a></td>
    <td><?php echo $this->escapeHtml($album->category);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>