<?php
// module/Album/view/album/album/add.phtml:
 
$title = 'Add Categories';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo "</br>";
echo $this->formRow($form->get('name'));
echo "</br>";
echo $this->formRow($form->get('position'));
echo "</br>";
echo $this->formSubmit($form->get('submit'));

// echo $this->formCollection($form);

echo $this->form()->closeTag();