<h1>Post List</h1>

<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Title</th>
			<th>Category</th>
			<th>Action</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach ($this->posts as $post):?>
			<tr>
				<td><?php

				echo ($post->getId())?></td>
				<td><?php echo ($post->getTitle())?></td>
				<td><?php echo ($post->getCategoryName())?></td>
				<td>
				
				</td>
			</tr>
		<?php endforeach;?>
	</tbody>
</table>
